In [4]:
import numpy as np
np_arr = np.arange(100000)

In [5]:
nu_list=[]
for i in range(10000):
    nu_list.append(i)

In [6]:
nu_list = [ i for i in range(10000)]

In [7]:
%%time
for i in range(100):
    sum(nu_list)

CPU times: user 8.57 ms, sys: 953 µs, total: 9.52 ms
Wall time: 13.8 ms


In [8]:
%%time 
for i in range(100):
    np.sum(np_arr)

CPU times: user 7.66 ms, sys: 2.21 ms, total: 9.87 ms
Wall time: 25.5 ms


In [9]:
vector = np.array([1,4,7,10],float)
vector

array([ 1.,  4.,  7., 10.])

In [10]:
type(vector)

numpy.ndarray

In [13]:
vector.shape

(4,)

# 2차원 배열 만들기 

In [15]:
martrix = np.array([[1,2,5,8],[2,3,4,9],[4,5,6,7]])
martrix

array([[1, 2, 5, 8],
       [2, 3, 4, 9],
       [4, 5, 6, 7]])

In [16]:
martrix.shape

(3, 4)

# 3차원 배열 만들기

In [25]:
tensor_list = [[[1,2,5,8],[2,3,4,9],[4,5,6,7]],
                [[1,2,5,8],[2,3,4,9],[4,5,6,7]],
                [[1,2,5,8],[2,3,4,9],[4,5,6,7]],
                [[1,2,5,8],[2,3,4,9],[4,5,6,7]]]
tensor = np.array(tensor_list)
tensor

array([[[1, 2, 5, 8],
        [2, 3, 4, 9],
        [4, 5, 6, 7]],

       [[1, 2, 5, 8],
        [2, 3, 4, 9],
        [4, 5, 6, 7]],

       [[1, 2, 5, 8],
        [2, 3, 4, 9],
        [4, 5, 6, 7]],

       [[1, 2, 5, 8],
        [2, 3, 4, 9],
        [4, 5, 6, 7]]])

In [27]:
tensor.shape

(4, 3, 4)

# Array Shape

### nidm & size
### N차원인 것을 알려주는 명령어

In [29]:
vector.ndim, martrix.ndim, tensor.ndim

(1, 2, 3)

In [32]:
import pandas as pd 


<module 'numpy' from '/Users/chan/opt/anaconda3/lib/python3.7/site-packages/numpy/__init__.py'>