In [1]:
a_list = [[1,2,3],['a','b','c']]
a_list[1][1]

'b'

In [4]:
import numpy as np
a_arr=np.array([[1,2,3],[2,3,4]])
a[1,1]

NameError: name 'a' is not defined

In [7]:
a= np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]],int)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [8]:
a[:2,:2]

array([[1, 2],
       [5, 6]])

In [9]:
a[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [15]:
a[1:,1:3]

array([[ 6,  7],
       [10, 11]])

In [27]:
a[0:,-2:4]

array([[ 3,  4],
       [ 7,  8],
       [11, 12]])

In [28]:
a[0:,2:4]

array([[ 3,  4],
       [ 7,  8],
       [11, 12]])

In [34]:
#a[1:,0:-1:2]
#a[1:,0::2]
a[1:,0:4:2]

array([[ 5,  7],
       [ 9, 11]])