In [1]:
import numpy as np
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
np.arange(0,5,0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [7]:
np.arange(0,5,0.5).tolist()

[0.0, 0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5]

In [8]:
np.arange(12).reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [10]:
x=np.arange(-1,1,100)
y=np.sin(x)

### ones,zeros and empty

In [18]:
np.zeros(shape=(10), dtype=np.int8) # 원소가 10개인 벡터 생성

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [23]:
np.ones((2,5)) # 2x5 - data값이 1인 실수 matrix 생성

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [25]:
np.empty((3,5)) #메모리가 초기화되어 있지 않음 , 즉 기억공간만 확보(쓰레기값 존재)

array([[-1.28822975e-231,  2.00390009e+000,  3.95252517e-323,
         0.00000000e+000,  0.00000000e+000],
       [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
         0.00000000e+000,  0.00000000e+000],
       [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
         0.00000000e+000, -1.28822975e-231]])

## Something like
### 기존의 ndarray의 shape 크기만큼 1,0 또는 empty array를 반환

In [33]:
test_matrix = np.arange(30).reshape(5,6)
test_matrix
np.ones_like(test_matrix)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [42]:
np.zeros_like(test_matrix)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [43]:
np.empty_like(test_matrix)

array([[-8070450532247928832,  3458773296047680510,                   21,
                           0,                    0,                    0],
       [                   0,                    0,                    0,
                           0,                    0,                    0],
       [                   0,                    0,                    0,
         7863896425567107377, -8070450532247928832, -8070450532247928832],
       [                  13,                    0,                    0,
                           0,                    0,                    0],
       [                   0,                    0,                    0,
                           0,                    0,                    0]])

## Identity(단위 행렬)

In [55]:
np.identity(n=3,dtype=np.int32) #n=단위 dtype = defalut = float

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int32)

In [60]:
np.identity(4) 

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## eye(대각선이 1인 행렬)

In [70]:
np.eye(3,5) # x = 행, y = 열, z = 시작위치

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [73]:
np.eye(3,6) #

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.]])

In [74]:
np.eye(3,5,-1)

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.]])

## diag(대각 행렬의 값 추출)

In [88]:
matrix = np.arange(16).reshape(4,4)
matrix

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [92]:
np.diag(matrix,0) #대각 행렬만 추출 # k = 시작 위치

array([ 0,  5, 10, 15])

## Random sampling
#0에서부터 1까지의 값중 임의의 값을 추출함(난수)

In [99]:
np.random.seed(2021)

In [105]:
np.random.uniform(0,1,10).reshape(2,5) # 균등분포 (최소, 최대 ,개수)

array([[0.5088309 , 0.43178618, 0.91593956, 0.70901564, 0.89065539],
       [0.58888561, 0.63682992, 0.34220894, 0.82379118, 0.30515077]])

In [103]:
np.random.normal(0,1,10).reshape(2,5) #정규분포(평군, 표준편차, 개수)

array([[-1.33620597,  0.30372151, -0.72015884,  2.5449146 ,  1.31729112],
       [ 0.0726303 , -0.25610814,  0.13801041,  1.14723599,  1.37626076]])