In [2]:
import numpy as np

In [3]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
a >5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [5]:
np.any(a>5), np.all(a>5)

(True, False)

In [6]:
np.any(a>10), np.all(a<10)

(False, True)

## Logical operation

In [8]:
a = np.array([1,3,0],float)
b = np.logical_and(a>0,a<3) # 0<a<3
b

array([ True, False, False])

In [11]:
c = np.logical_or(a<0, a>3)
c

array([False, False, False])

In [12]:
np.where(a>0)

(array([0, 1]),)

In [20]:
# Nan --> Not a number , np.nan
# inf --> infinite , np.inf
x = np.array([1, np.nan, np.Inf])
x

array([ 1., nan, inf])

In [21]:
np.isnan(x)

array([False,  True, False])

In [25]:
np.isnan(x).sum()

1

In [22]:
np.isinf(x)

array([False, False,  True])

In [26]:
X = np.arange(1000,dtype=np.float)
X[500]=np.nan

In [31]:
np.isnan(X)
# 너무많은 데이터중 확인하기 위해 
np.isnan(X).sum()
#와 같이 사용   

1

In [32]:
np.isfinite(x)

array([ True, False, False])

In [35]:
len(x) - np.isfinite(x).sum()
#무한이 아닌 것들

2

## armax & argmin
## 인덱스를 출력함

In [36]:
a = np.array([1,2,4,5,8,10,87,23,4])
a

array([ 1,  2,  4,  5,  8, 10, 87, 23,  4])

In [37]:
np.argmax(a)
#인덱스를 출력함

6

In [38]:
np.argmin(a)

0

In [39]:
a = np.array([[1,2,4,7],[9,88,6,45],[8,78,23,3]])
a

array([[ 1,  2,  4,  7],
       [ 9, 88,  6, 45],
       [ 8, 78, 23,  3]])

In [40]:
np.argmax(a, axis=0)

array([1, 1, 2, 1])

In [42]:
np.argmin(a, axis=1)

array([0, 2, 3])

In [45]:
np.max(a)

88