## Numpy Boolean and fancy index

In [1]:
import numpy as np

## Boolean index

In [3]:
test_array = np.array([1,4,0,2,3,8,9,7],float)
test_array > 3

array([False,  True, False, False, False,  True,  True,  True])

In [4]:
# filter
test_array[test_array>3]

array([4., 8., 9., 7.])

In [6]:
condition = test_array >3
test_array[condition]

array([4., 8., 9., 7.])

## Fancy Index

In [8]:
a = np.arange(2,9,2)
a

array([2, 4, 6, 8])

In [16]:
b = np.array([0,2,1,3,0,2], dtype=np.int32)
b

array([0, 2, 1, 3, 0, 2], dtype=int32)

In [17]:
a[b]

array([2, 6, 4, 8, 2, 6])