In [2]:
import numpy as np

## 1번

In [20]:
a = np.arange(50)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

## 2번

In [21]:
b= a[::-1]
b

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

## 3번

In [66]:
c=np.zeros(shape=(10), dtype=np.int8)
c[4]=1
c

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0], dtype=int8)

## 4번

In [69]:
d=np.arange(9)
d
d.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## 5번

In [135]:
a = np.array([1,2,0,0,4,0])
a[a>0]

array([1, 2, 4])

## 6번

In [77]:
l=np.identity(n=3,dtype=np.int32)
l

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int32)

## 7번

In [146]:
a=np.random.randint(1, 5, size=(3, 3))
a

array([[1, 2, 2],
       [2, 2, 4],
       [1, 2, 3]])

In [126]:
max=np.max(a)
max

4

In [127]:
min=np.min(a)
min


1

## 8번

In [128]:
a.mean(axis=0,dtype=np.int32)

array([2, 2, 2], dtype=int32)

In [129]:
a.mean(axis=1,dtype=np.int32)

array([3, 1, 2], dtype=int32)

## 9번

In [171]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [161]:
a=np.identity(n=5,dtype=np.int32)


array([[0, 2, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 2, 0],
       [0, 0, 0, 0, 2],
       [0, 0, 0, 0, 0]], dtype=int32)

In [236]:
a=+np.eye(5,5,1)+np.eye(5,5,0)+np.eye(5,5,0)+np.eye(5,5,-1)+np.eye(5,5,-1)+np.eye(5,5,-1)
x = a.astype('int')
x

array([[2, 1, 0, 0, 0],
       [3, 2, 1, 0, 0],
       [0, 3, 2, 1, 0],
       [0, 0, 3, 2, 1],
       [0, 0, 0, 3, 2]])